spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 146317225694-sfbbsfjbgp98pl2nitav4j00j5gl89i2.apps.googleusercontent.com
            client-secret: rq6d5GCotq_k4mzUCnXxBCx
          facebook:
            client-id: 133914262008260
            client-secret: 8d90ade2d7490c03b81514341a84878a

custom:
  oauth2:
    kakao:
      client-id: f74add7b54b077a0af9d64103f00fe76


#####################################################################################################
########## 스프링부트 시큐리트 OAuth2 API 에서는 구글, 페이스북 등에 대한 기본 정보를 제공하기에 삭제 ############
#####################################################################################################
#facebook:
#  client:
#    clientId: 133914262008260
#    clientSecret: 8d90ade2d7490c03b81514341a84878a
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,eamil,link
#
#google:
#  client:
#    clientId: 146317225694-sfbbsfjbgp98pl2nitav4j00j5gl89i2.apps.googleusercontent.com
#    clientSecret: rq6d5GCotq_k4mzUCnXxBCx
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao:
#  client:
#    clientId: f74add7b54b077a0af9d64103f00fe76
#    accessTokenUri: https://kauth.kakao.com/oauth/token
#    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me